# Generated by Django 5.1.5 on 2025-10-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
