# Generated by Django 5.1.5 on 2025-10-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
